theme = "solarized_light"
# theme = "gruvbox_light"

[editor]
line-number = "relative"
mouse = true
auto-format = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-global = false
hidden = false


[keys.normal]
C-w = ":bc"
y = ":clipboard-yank"
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
[keys.normal.space]
p = "command_palette"
w = ":write"
"space" = "goto_last_accessed_file"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
