k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: arn:aws:eks:eu-west-1:949316342391:cluster/toutatis-testing-eks
  currentCluster: arn:aws:eks:eu-west-1:949316342391:cluster/toutatis-testing-eks
  keepMissingClusters: false
  clusters:
    arn:aws:eks:eu-west-1:949316342391:cluster/toutatis-production-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - production
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:949316342391:cluster/toutatis-recette-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - recette
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:949316342391:cluster/toutatis-staging-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:949316342391:cluster/toutatis-testing-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - testing
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/66/8xbktlrd16v_xt64qjzfr61c0000gn/T/k9s-screens-emmanuellongeau
  disablePodCounting: false
